spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://38.242.251.70:9888/test}
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:sblx1nzquzpajj1y}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:5}
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.ceylon_pick.ceylon: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
